extent.reporter.spark.start=true
#extent.reporter.pdf.start=true
extent.reporter.spark.out=test-output/SparkReport1/Spark.html
extent.reporter.spark.config=src/test/resources/extent-config.xml
extent.reporter.spark.vieworder=dashboard,test,category,exception,author,device,log
screenshot.dir=test-output/
screenshot.rel.path=../
basefolder.name=Automation_Reports/Report
basefolder.datetimepattern=d-MMM-YY HH-mm-ss