#loginForm: //*[@id='loginForm']
loginForm: //p[contains(concat(' ', normalize-space(@class), ' '), ' fontheader ')]
userid: //input[@id='userid']
password: //input[@id='password']
btn-login-submit: //input[@id='btn-login-submit']
index-menu-label://span[@class='index-menu-label']
btn://span[contains(text(), 'Yes')]
----ETF
tabItem-4423549: //span[contains(@id,'tabItem-310476')]
right: //span[contains(text(), 'SGD')]
clickETFTab://a[contains(text(),'ETF')]
ClientAcctInput://*[@class='ClientAcctInput']
searchInput: (//*[@name='searchInput'])[2]
searchMatch: (//div[contains(@class,'SearchProduct ST')])[1]
select2-selection__arrow: //span[@class='select2-selection__arrow']
ST-Btn-Submit-mdl-button-button-trade-button-trade--huge-button-trade--buy: //input[@class='ST-Btn-Submit mdl-button button-trade button-trade--huge button-trade--buy']
ST-QuantityCombo: //input[@class='ST-QuantityCombo']
ST-StopLimitCombo: //input[@class='ST-PriceCombo']
MsgContent: //*[@id='MsgContent']
ui-button-text: (//button[contains(@class,'btn p-btn mdl-button mdl-js-button mdl-button--secondary')])[3]
---EQ
opt-buy: //li[@class='opt-buy text-upper selected'][1]
opt-short: //li[@class='opt-short st-opt-short-sell text-upper sel-right']
opt-sell: //li[@class='opt-sell text-upper']
ST-Btn-Submit_short_Sell: //input[@class='ST-Btn-Submit mdl-button button-trade button-trade--huge button-trade--shortsell']
ST-Btn-Submit_Sell: //input[@class='ST-Btn-Submit mdl-button button-trade button-trade--huge button-trade--sell']
ST-PriceCombo: //*[@class='ST-PriceCombo']
stockTradeTab://a[contains(text(), 'Stocks')][1]
selected: //li[contains(text(), 'Cash')]
presession: //li[contains(text(), 'Day')][1]
gtd: //li[contains(text(), 'GTD')][1]
orderNo2: (//a[@class='orderNo'])[1]
icon-close: //i[@class='icon-close']
trade-value: (//span[@class='trade-value ST-Confirm-CliAcct'])[1]
trade-value3: //span[@class='trade-value ST-Confirm-OrderType']
trade-value-ST-Confirm-Action-text-upper-trade-color-buy: //span[@class='trade-value ST-Confirm-Action text-upper trade-color-buy']
trade-value-ST-Confirm-Action-text-upper-trade-color-shortsell: //span[@class='trade-value ST-Confirm-Action text-upper trade-color-shortsell']
trade-value-ST-Confirm-Action-text-upper-trade-color-sell: //span[@class='trade-value ST-Confirm-Action text-upper trade-color-sell']
trade-value7: //span[@class='trade-value ST-Confirm-Qty']
trade-value10: //span[@class='trade-value ST-Confirm-TradeType']
trade-value8: //span[@class='trade-value ST-Confirm-SettCurr']
trade-value9: //span[@class='trade-value ST-Confirm-TimeInForce']
ST-Btn-Confirm_buy: //input[@class='ST-Btn-Confirm mdl-button button-trade button-trade--huge button-trade--buy']
ST-Btn-Confirm_shortsell: //input[@class='ST-Btn-Confirm mdl-button button-trade button-trade--huge button-trade--shortsell']
ST-Btn-Confirm_sell: //input[@class='ST-Btn-Confirm mdl-button button-trade button-trade--huge button-trade--sell']
getActionTypeOrderDetailsETF: //table[@class='detailTable']//tr[3]//td[2]
getQtyOrderDetailsETF: //table[@class='detailTable']//tr[6]//td[2]
getProductOrderDetailsETF: //table[@class='detailTable']//tr[2]//td[4]
getPaymentTypeOrderDetailsETF: //table[@class='detailTable']//tr[3]//td[4]
getSettlementOrderDetailsETF: //table[@class='detailTable']//tr[6]//td[4]
getorderTypeOrderDetailsETF: //table[@class='detailTable']//tr[5]//td[4]
getStatusOrderDetailsETF: //table[@class='histable']//a[@class='OrderStatus_Status']

