loginIdField://*[@id='userid']
passwordField://*[@id='password']
loginForm://*[@id='loginForm']
loginButton://*[@id='btn-login-submit']
emptyLoginMsg://p[@id='MsgContent']
wrongLoginMsg://*[@id='loginForm']//li[contains(text(),'Incorrect login')]