name: OrangeHRM Automation CI

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  automation-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Verify Chrome
        run: chrome --version

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}

      - name: Install Dependencies
        run: mvn clean install -DskipTests

      - name: Print Maven Dependencies
        run: mvn dependency:tree

      - name: Run Automation Tests
        run: mvn test

      - name: Upload Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestReports
          path: |
            target/
            test-output/
